export const CONSTANTS = {
  UP              : 'up',
  LEFT            : 'left',
  DOWN            : 'down',
  RIGHT           : 'right',
  COL_PLAYER      : Math.pow(2, 0),
  COL_ENEMY       : Math.pow(2, 1),
  COL_GROUND      : Math.pow(2, 2),
  FADE_DURATION   : 1000,
  SPEED_SERVER    : 180,
  ATTACK          : 'attack',
  HIT             : 'hit',
  DEATH           : 'death',
  REGISTER        : 'account.register',
  LOGIN           : 'account.login',
  LOGOUT          : 'account.logout',
  LOGGED_IN       : 'account.logged-in',
  LOGGED_OUT      : 'account.logged-out',
  VERIFY_ACCOUNT  : 'account.verify',
  CREATE_CHARACTER: 'character.create',
  CHARACTER_CREATED: 'character.created',
  GET_CHARACTERS  : 'character.get',
  DELETE_CHARACTER: 'character.delete',
  SELECT_CHARACTER: 'character.select',
};
